import type { Metadata } from "next";
import Link from "next/link";
import { RibbonMark } from "@/components/ribbon-mark";
import { SettingsLink } from "@/components/settings-link";
import { CopyField, ProfileForm } from "@/components/share/profile-form";
import { profileCardSvg } from "@/lib/profile/card";
import { getProfile, siteUrl, statsFor } from "@/lib/profile/data";
import { linkedInAddUrl, suggestHandle } from "@/lib/profile/logic";
import { milestonesFor } from "@/lib/profile/milestones";
import { requireUser } from "@/lib/session";

export const metadata: Metadata = { title: "Share your progress" };

export default async function SharePage() {
  const user = await requireUser();
  const saved = await getProfile(user.id);
  const profile = saved ?? {
    handle: suggestHandle(user.name || user.email),
    enabled: false,
    showName: true,
  };
  const site = siteUrl();
  const stats = await statsFor(
    user.id,
    profile.handle,
    profile.showName ? user.name : profile.handle,
  );
  const live = saved?.enabled === true;
  const local = /localhost|127\.0\.0\.1/.test(site);
  const base = `${site}/u/${profile.handle}`;
  const now = new Date();

  const readme = `<a href="${base}">
  <picture>
    <source media="(prefers-color-scheme: dark)" srcset="${base}/card.svg?theme=dark">
    <img alt="My reading on Ribbon" src="${base}/card.svg">
  </picture>
</a>`;
  const badges = ["level", "streak", "book"]
    .map((id) => `[![Ribbon ${id}](${base}/badges/${id}.svg)](${base})`)
    .join(" ");

  return (
    <div className="home">
      <header className="home-bar">
        <Link href="/" className="flex items-center gap-2.5">
          <RibbonMark className="h-6 w-[18px] text-accent" />
          <span className="font-serif text-lg font-semibold">Ribbon</span>
        </Link>
        <SettingsLink />
      </header>

      <main className="home-main set-main">
        <nav aria-label="Breadcrumb" className="ov-crumbs">
          <Link href="/">Home</Link>
          <span aria-hidden="true">/</span>
          <span>Share</span>
        </nav>
        <div>
          <h1 className="set-title">Share your progress</h1>
          <p className="home-muted lb-intro">
            Show your level, streak, and badges on GitHub, LinkedIn, or anywhere else.
          </p>
        </div>

        <section className="home-card set-section share-top" aria-labelledby="profile-title">
          <div>
            <h2 id="profile-title" className="home-section-title">
              Your profile
            </h2>
            <ProfileForm
              handle={profile.handle}
              enabled={profile.enabled}
              showName={profile.showName}
              name={user.name}
              site={site}
            />
          </div>
          <figure className="share-preview">
            {/* Our own SVG, built with escaped text. */}
            <div
              className="share-card"
              // biome-ignore lint/security/noDangerouslySetInnerHtml: generated by profileCardSvg, all text escaped
              dangerouslySetInnerHTML={{ __html: profileCardSvg(stats, "light") }}
            />
            <figcaption className="home-muted">
              {live ? (
                <Link href={`/u/${profile.handle}`} className="text-accent hover:underline">
                  View your public profile
                </Link>
              ) : (
                "Preview. Turn the profile on to share it."
              )}
            </figcaption>
          </figure>
        </section>

        {live && local && (
          <p className="share-warn">
            You're on {site}. GitHub and LinkedIn can't load images from your own computer, so these
            links work once Ribbon is live.
          </p>
        )}

        {live && (
          <>
            <section className="home-card set-section" aria-labelledby="github-title">
              <h2 id="github-title" className="home-section-title">
                GitHub
              </h2>
              <p className="home-muted">
                Paste into your profile README (the repository named after your username). The card
                follows GitHub's light or dark mode and updates as you read.
              </p>
              <CopyField label="Profile card" value={readme} />
              <CopyField label="Small badges" value={badges} />
            </section>

            <section className="home-card set-section" aria-labelledby="linkedin-title">
              <h2 id="linkedin-title" className="home-section-title">
                LinkedIn
              </h2>
              <p className="home-muted">
                Add a milestone to the Licenses &amp; certifications section of your profile. It
                shows Ribbon as the issuer and links to a page that checks it live. These are
                reading achievements you tracked yourself, not certificates from the book's
                publisher.
              </p>
              <ul className="share-milestones">
                {milestonesFor(stats).map((m) => (
                  <li key={m.id} className="share-milestone">
                    <span className="share-mark" aria-hidden="true">
                      {m.mark}
                    </span>
                    <span className="min-w-0 flex-1">
                      <span className="pub-badge-name">{m.name}</span>
                      <span className="home-muted pub-badge-how">{m.detail}</span>
                    </span>
                    <a
                      className="share-linkedin"
                      href={linkedInAddUrl({
                        name: m.name,
                        issuer: "Ribbon",
                        issued: now,
                        credentialUrl: `${base}/badge/${m.id}`,
                        credentialId: `${profile.handle}-${m.id}`,
                      })}
                      target="_blank"
                      rel="noopener noreferrer"
                    >
                      Add to LinkedIn
                    </a>
                  </li>
                ))}
              </ul>
              <a
                className="ov-secondary share-post"
                href={`https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(base)}`}
                target="_blank"
                rel="noopener noreferrer"
              >
                Share a post with your profile
              </a>
            </section>

            <section className="home-card set-section" aria-labelledby="anywhere-title">
              <h2 id="anywhere-title" className="home-section-title">
                Anywhere else
              </h2>
              <p className="home-muted">
                Your profile link shows a preview card on LinkedIn, X, WhatsApp, and Slack. Or
                download the image and post it yourself.
              </p>
              <CopyField label="Profile link" value={base} />
              <div className="set-actions">
                <a
                  className="ov-secondary"
                  href={`/u/${profile.handle}/card.png?download`}
                  download
                >
                  Download image (PNG)
                </a>
              </div>
            </section>
          </>
        )}
      </main>
    </div>
  );
}
